export const FUEL_REFUELING = 'FUEL_REFUELING';
export const MAINTENANCE = 'MAINTENANCE';
export const PURCHASE_OF_SPARE_PARTS = 'PURCHASE_OF_SPARE_PARTS';
export const CLEANING = 'CLEANING';
export const ENGINE_TUNING = 'ENGINE_TUNING';
export const SERVICE = 'SERVICE';
